#!/bin/sh

echo "################################################"
echo "# BSPWM/SXHKD"
echo "#     - Screenshot"
echo "#     - Power saving"
echo "#     - Lock script"
echo "#     - Config Dunst"
echo "#     - Floating windows / scratchpad"
echo "# Conky"
echo "#     - Install / config"
echo "# LightDM"
echo "#     - Theme greeter"
echo "# Tmux"
echo "# Snapd"
echo "################################################"
