#!/bin/sh

echo "BSPWM/SXHKD"
echo "      - Screenshot"
echo "      - Power saving"
echo "      - Lock script"
echo "      - Floating windows / scratchpad"
echo "Rofi as dmenu"
echo "Conky"
echo "      - Clock"
echo "Spicetify"
echo "      - Transparency"
echo "Tmux"
echo "      - Notetaking"
echo "Vagrant"
echo "Docker"
echo "Nmap"
echo "Wireshark"
