#!/bin/sh

echo "BSPWM/SXHKD"
echo "      - rounded windows"
echo "      - Screenshot"
echo "      - Power saving"
echo "      - Lock script"
echo "      - Floating windows / scratchpad"
echo "Polybar"
echo "      - Figure fonts out"
echo "Dunst"
echo "      - Nord theme"
echo "Spicetify"
echo "      - Transparency"
echo "Tmux"
echo "      - Troubleshoot/rewrite ws script"
echo "      - TUI wrapper"
echo "Vagrant"
echo "Docker"
echo "Nmap"
echo "Wireshark"
