#! /bin/sh

bspc -r "*"

# ----- Autostart ----- #

sxhkd &
dunst &
$HOME/.fehbg
$HOME/.config/polybar/start_polybar.sh


# ----- Single Monitor ----- #
bspc monitor -d  1 2 3 4 5 6 7 8 9 0


# ----- General Settings ----- #

    # Gaps
bspc config window_gap              10
bspc config top_padding             30
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0
bspc config border_width            5

    # Colors
bspc config normal_border_color     \#44475a
bspc config active_border_colorj    \#bd93f9
bspc config focused_border_color    \#ff79c6
bspc config presel_feedback_color   \#50fa7b

bspc config border_width            2
bspc config window_gap              12
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

