#! /bin/sh

bspc -r "*"

# ----- Autostart ----- #

    # Variables
export BROWSER="/usr/bin/firefox"
export TERMINAL="/usr/bin/termite"
export EDITOR="/usr/bin/nvim"
export GEDITOR="/usr/bin/code"
export FILE_EXPLORER="/usr/bin/nautilus"

    # Procs
picom &
sxhkd &
dunst &
$HOME/.fehbg
$XDG_CONFIG_HOME/polybar/start_polybar.sh


# ----- Monitors and Desktops ----- #
bspc monitor -d  1 2 3 4 5 6 7 8 9 0

#i=1
#for monitor in $(bspc query -M); do
#bspc monitor $monitor \
#        -n "$i" \
 #       -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
#    let i++
#done
#NMON=$i
#unset i

# ----- General Settings ----- #

    # Gaps
bspc config window_gap              10
bspc config top_padding             25
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0
bspc config border_width            5

    # Colors
bspc config normal_border_color     "#d8dee9"
bspc config active_border_color     "#3b4252"
bspc config focused_border_color    "#b48ead"
bspc config presel_feedback_color   "#81a1c1"
bspc config urgent_border_color     "#bf616a"

    # Visual Options
bspc config split_ratio             0.50
bspc config border_width            2
bspc config window_gap              12
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   false
bspc config auto_alternate          true
bspc config auto_cancel             true
