#! /bin/sh

bspc -r "*"

# ----- Autostart ----- #

    # Setup env
source $HOME/.profile

    # Disable Caps lock
setxkbmap -option caps:escape

    # Kill old Procs
pkill -USR1 -c picom
pkill -USR1 -c sxhkd
pkill -USR1 -c dunst
pkill -USR1 -c unclutter


    # Start Procs
picom &
sxhkd &
dunst &
unclutter --timeout 5 &
bg_apply
polybar_start


# ----- Monitors and Desktops ----- #
bspc monitor -d  1 2 3 4 5 6 7 8 9 0
bspc monitor DP2-3 -d 1 2 3 4 5 6 7 8 9 0

# ----- General Settings ----- #

    # Monitors
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

    # Gaps
bspc config window_gap                  10
bspc config top_padding                 25
bspc config bottom_padding              0
bspc config right_padding               0
bspc config left_padding                0
bspc config border_width                5

    # Colors
bspc config normal_border_color         "#d8dee9"
bspc config active_border_color         "#3b4252"
bspc config focused_border_color        "#b48ead"
bspc config presel_feedback_color       "#81a1c1"
bspc config urgent_border_color         "#bf616a"

    # Visual Options
bspc config split_ratio                 0.50
bspc config border_width                2
bspc config window_gap                  12
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config focus_follows_pointer       false
bspc config auto_alternate              true
bspc config auto_cancel                 true
