#!/bin/bash

# This script automates the process of syncing my obsidian files with gitlab

gstatus='git status --porcelain'

if [ ${#gstatus} -ne 0 ]; then
    git add --all
    sleep 10
    git commit -m "Automated sync ($HOST): $gstatus"
    sleep 10
    git pull --rebase
    sleep 10
    git push
fi
