#!/bin/zsh

# This script attaches / creates a tmux session for the cwd.  Intended as a base configuration to be build and saved on a per session basis

SESSION=$(basename $PWD)

function ws_up() {
        # Create new session with the name of the directory it was launched
    tmux new-session -d -s $SESSION

        # Project Root
    tmux rename-window -t $SESSION:0 "root"


    # TODO - Add a pane for git status

    tmux respawn-pane -t $SESSION:0.0 -k "ranger $(pwd)"

        # Attach
    #tmux select-pane -t $SESSION:0.0
    tmux attach-session -t $SESSION
}

tmux attach-session -t $SESSION

if [ $? -ne 0 ]; then
    ws_up
    echo "Created new session: $SESSION"
else
    echo "Attached to pre-existing $SESSION"
fi
